name: Playwright Tests

on: 
  push:
    branches: [ master ]

jobs:
  playwright-tests:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/playwright:v1.44.1-jammy
      env: 
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo 'Start the shopping store app'
          ./shopping-store-linux-amd64 &
          echo 'Install dependencies from lockfile'
          npm ci # it installs all packages from pakcage-lock.json
          echo 'Run playwright tests'
          npm run test:ci